
'
Align RNAseq reads to Ce10

DESCRIPTION
-----------
Analysis was performed by: Milou Meeuse (alignment performed on 18-07-2018)

This code allows the user to align the RNAseq reads to the C.elegans genome (Ce10) using QuasR

This script consists of the following steps: 
  (1) align reads to genome
  (2) make BigWig files
  (3) quality control of sequencing reads and alignment
  

EXPERIMENT DESCRIPTION
----------------------
Experiment was performed by: Milou Meeuse
Experiment identifier in GNomEx: 1660R
Sequencing protocol: TruSeq Illumina total RNA, HiSeq 50 cycle single end reads, HiSeq 2500, submitted 2018-06-29 

aim: investigate gene expression changes upon depletion of grh-1::degron::3xflag by adding 250 uM auxin (pl) or ethanol (min) at 21h of development at 20 degr in liquid. 
     RNA was sampled from 24.5h until 30h at 30 min intervals

REFERENCES
----------
https://bioconductor.org/packages/devel/bioc/vignettes/QuasR/inst/doc/QuasR.html


INPUT
-----
Data format: 
-overview of samples: samples.txt file generated by Sarah Carl
-sequencing reads: fastq.gz files on /work2/ggrossha/milou/RNAseq1660
-reference genome: BSgenome.Celegans.UCSC.ce10


USAGE
-----
run qAlign, qExportWig and qQCReport



OUTPUT
------
-bam files
-QCreport
-BigWig files





REQUIREMENTS
------------
This script requires the following packages to be installed:
-"R version 3.5.1 Patched (2018-11-02 r75543)"
-genome	BSgenome.Celegans.UCSC.ce10, aligner	Rbowtie, aligner.version	1.20.0, QuasR.version	1.20.0


"'






setwd('/work2/ggrossha/milou/RNAseq1660')

library('QuasR')
library('BSgenome.Celegans.UCSC.ce10')


#(1)---align reads of RNA-seq to c.elegans genome---
clObj <- makeCluster(10)
proj <- qAlign('samples.txt', 'BSgenome.Celegans.UCSC.ce10', alignmentsDir = 'bam', clObj = clObj, splicedAlignment = TRUE)

#(2)---export bw files---
exportwig <- qExportWig(proj, createBigWig = TRUE, binsize = 50)

#(3)---Quality Control report---
setwd("/tungstenfs/scratch/ggrossha/meeumilo/scripts/RNAseq_GRH-1degron/1660R/2018-07-18 AlignmentCe10")
qQCReport(proj, pdfFilename="2018-07-20 QCReport.pdf")


